### PR TITLE
Updated ETL readme

### PR DESCRIPTION
**Pull request by vince4188**
Fixes #

## Changes proposed in this pull request

  -
  -
  -

### CODE REVIEW

**Review by NotShin — CHANGES_REQUESTED** [review]
Add code blocks for readability and any necessary documentation.

**Comment by vince4188** [comment]
Added Changes

**Review by NotShin — CHANGES_REQUESTED** [review]
Numbered bullets need updates. Speak with me tomorrow.

**Review by NotShin — APPROVED** [review]
gtg

**Pull request merged**
