### PR TITLE
Eric saetz

### PR DESCRIPTION
**Pull request by EricSaetz**
Added my file.

### CODE REVIEW

**Comment by EricSaetz** [comment]
Added name files

**Review by NotShin — CHANGES_REQUESTED** [review]
Naming convention not followed -> All lowercase with dashes (-) instead of spaces.
Documentation for Java code not included.
Maven project folder missing

**Review by terrancemount — APPROVED** [review]

**Review by NotShin — CHANGES_REQUESTED** [review]
Modify names/EricSaetz.txt to follow convention:
- All lowercase with dashes (-) instead of spaces (i.e. names/eric-saetz).

Remove all .java files:
- These should be included with the maven project folder and submitted from a spark feature branch.

**Review by NotShin — CHANGES_REQUESTED** [review]
Remove .txt from filename: names/eric-saetz.txt

**Review by NotShin — APPROVED** [review]
gtg

**Pull request merged**
